// <auto-generated />
using System;
using BridgeBotNext.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BridgeBotNext.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20191116192805_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("BridgeBotNext.Entities.Connection", b =>
                {
                    b.Property<long>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeftConversationConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RightConversationConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionId");

                    b.HasIndex("LeftConversationConversationId");

                    b.HasIndex("RightConversationConversationId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("BridgeBotNext.Entities.Conversation", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("BridgeBotNext.Entities.Person", b =>
                {
                    b.Property<string>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("BridgeBotNext.Providers.Tg.TgPerson", b =>
                {
                    b.HasBaseType("BridgeBotNext.Entities.Person");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("TgPerson");
                });

            modelBuilder.Entity("BridgeBotNext.Providers.Vk.VkPerson", b =>
                {
                    b.HasBaseType("BridgeBotNext.Entities.Person");

                    b.HasDiscriminator().HasValue("VkPerson");
                });

            modelBuilder.Entity("BridgeBotNext.Entities.Connection", b =>
                {
                    b.HasOne("BridgeBotNext.Entities.Conversation", "LeftConversation")
                        .WithMany()
                        .HasForeignKey("LeftConversationConversationId");

                    b.HasOne("BridgeBotNext.Entities.Conversation", "RightConversation")
                        .WithMany()
                        .HasForeignKey("RightConversationConversationId");
                });
#pragma warning restore 612, 618
        }
    }
}
